on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n newcontain111aa -g newcontain111aa848a-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n newcontain111aa --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n newcontain111aa --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n newcontain111aa --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: newcontain111aa.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t newcontain111aa.azurecr.io/tothemoon:${{ github.sha }} --label dockerfile-path=.devcontainer/Dockerfile
        docker push newcontain111aa.azurecr.io/tothemoon:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_tothemoon_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep tothemoon95c7 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace tothemoon95c7`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: tothemoon95c7
        container-registry-url: newcontain111aa.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: tothemoondockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: tothemoon95c7
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          newcontain111aa.azurecr.io/tothemoon:${{ github.sha }}
        imagepullsecrets: |
          tothemoondockerauth   
